require('./product-mapper/map-decision-core-handoff-to-product-mainline.test');
require('./product-mapper/build-evidence-drawer-state.test');
require('./product-mapper/no-decision-core-imports.test');
require('./product-mapper/rich-handoff-mapping.test');
require('./product-mapper/rich-golden-fixtures.test');
require('./product-workspace/build-topic-workspace-view-state.test');
require('./product-workspace/workspace-interaction-state.test');
require('./ui-flow/generate-local-topic-draft.test');
require('./ui-flow/local-topic-flow.test');
